# Generated by Django 4.2 on 2025-07-13 01:50

import datetime
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('discount_price', models.FloatField()),
                ('image', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('MFG_DT', models.DateField(default=datetime.datetime(2025, 7, 13, 7, 20, 28, 142676))),
                ('EXP_DT', models.DateField(default=shop.models.get_future_datetime)),
            ],
        ),
    ]
