# Generated by Django 4.2 on 2025-07-13 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MFG_DT',
            field=models.DateField(default=datetime.datetime(2025, 7, 13, 7, 24, 0, 209446)),
        ),
    ]
