# Generated by Django 5.2.1 on 2025-07-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=200)),
                ('Item_descr', models.CharField(max_length=200)),
                ('unit_price', models.IntegerField()),
            ],
        ),
    ]
