# Generated by Django 4.2 on 2025-07-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq9LhDfNFGvhQm1vx6I3gkDNi5M5r9tRSKqtr8qATPESYBsSIJNjdzr1iwqINoN_XcJ9U&usqp=CAU', max_length=500),
        ),
    ]
